name: skynet-handler-openid-auth-plugin
description: Adiciona a sua stack uma autenticação e autorização baseado em algum provider OpenID informado.
displayName: OpenPolicyAgent Based Auth
types:
  - app
inputs:
  - label: Uri de integração da lambda de autorização (OPA) já existente.
    type: text
    name: lambda_integration_uri
    required: true
    default: ''

hooks:
  - type: edit
    trigger: after-render
    path: infra/lib/{{service_name}}-service-stack.ts
    changes:
      - search:
          string: "const openApiServicesProps = {"
          insert-after:
            snippet: snippets/integration-uri-add.txt
  - type: edit
    trigger: after-render
    path: infra/spec/{{spec_file_name}}.yaml
    changes:
      - search:
          string: 'components:'
          insert-after:
            snippet: snippets/spec-auth-add.txt
          when:
            not-exists: 'authLambdaIntegrationUri: '
  - type: run
    trigger: after-render
    mac:
      - npm run infra:install:openapi
      - npm run infra:format:fix
      - npm run infra:build:cdk
      - npm run source:setup:openapi
    linux:
      - npm run infra:install:openapi
      - npm run infra:format:fix
      - npm run infra:build:cdk
      - npm run source:setup:openapi
    windows:
      - npm.cmd run infra:install:openapi
      - npm.cmd run infra:format:fix
      - npm.cmd run infra:build:cdk
      - npm.cmd run source:setup:openapi

